In [1]:
from sklearn.metrics import adjusted_rand_score
from sklearn.metrics import fowlkes_mallows_score
import pandas as pd

In [3]:
df1= pd.read_csv('/project/zerze/edayalam/primitive_clustering/combined_clusters/combined_bp1.csv')
df1

    UniProt ID      Protein  Cluster
0       Q96MR9  ZN560_HUMAN        0
1       Q15319  PO4F3_HUMAN        0
2       Q9UL58  ZN215_HUMAN        0
3       O60765  Z354A_HUMAN        0
4       P49910  ZN165_HUMAN        0
..         ...          ...      ...
861     Q9Y5R6  DMRT1_HUMAN       18
862     Q02962   PAX2_HUMAN       18
863     Q06710   PAX8_HUMAN       18
864     Q02548   PAX5_HUMAN       18
865     O94993  SOX30_HUMAN       18

[866 rows x 3 columns]

In [4]:
df2= pd.read_csv('/project/zerze/edayalam/primitive_clustering/combined_clusters/combined_bp2.csv')
df2

     UniProt ID      Protein  Cluster
0        Q8IYH5   ZZZ3_HUMAN        0
1        P23497  SP100_HUMAN        0
2        Q13342  SP140_HUMAN        0
3        Q8N3X6  LCORL_HUMAN        0
4        Q15361   TTF1_HUMAN        0
...         ...          ...      ...
1077     Q9H4T2  ZSC16_HUMAN       21
1078     Q9UPG8  PLAL2_HUMAN       21
1079     Q96BR6  ZN669_HUMAN       21
1080     Q86TJ5  ZN554_HUMAN       21
1081     Q6NX45  ZN774_HUMAN       21

[1082 rows x 3 columns]

In [5]:
df1.loc[1]

UniProt ID         Q15319
Protein       PO4F3_HUMAN
Cluster                 0
Name: 1, dtype: object

In [6]:
df = pd.merge(df1, df2, on='UniProt ID', how='inner')
df

    UniProt ID    Protein_x  Cluster_x    Protein_y  Cluster_y
0       Q15319  PO4F3_HUMAN          0  PO4F3_HUMAN         14
1       P49910  ZN165_HUMAN          0  ZN165_HUMAN         21
2       Q6ZS27  ZN662_HUMAN          0  ZN662_HUMAN         11
3       Q9BYM8  HOIL1_HUMAN          0  HOIL1_HUMAN         21
4       Q68EA5  ZNF57_HUMAN          0  ZNF57_HUMAN         16
..         ...          ...        ...          ...        ...
564     O95935  TBX18_HUMAN         18  TBX18_HUMAN         13
565     Q8NEA6  GLIS3_HUMAN         18  GLIS3_HUMAN         14
566     Q9UMR3  TBX20_HUMAN         18  TBX20_HUMAN          9
567     Q02962   PAX2_HUMAN         18   PAX2_HUMAN         14
568     O94993  SOX30_HUMAN         18  SOX30_HUMAN         15

[569 rows x 5 columns]

In [8]:
l1,l2= df['Cluster_x'], df['Cluster_y']

In [9]:
print (adjusted_rand_score(l1,l2))

0.07298569968950167

In [10]:
print (fowlkes_mallows_score(l1,l2))

0.1652031237467028

### after dropping the negative cluster labels i.e. noise points

In [36]:
# Drop rows with any negative values
df2 = df[(df.drop(columns='UniProtID') >= 0).all(axis=1)]
df2

,UniProtID,102_CLabels_fractions_kappa,3_CLabels_fractions_kappa,3_CLabels_fractions,103_CLabels_fractions,ED_3_CLabels_fractions_kappa
0,Q9H8Y5,72,0,0,55,0
1,O60678,87,0,0,38,0
2,Q96JM3,38,0,0,33,0
3,Q86YF9,67,0,0,5,0
5,Q96JM7,67,0,0,48,0
...,...,...,...,...,...,...
1259,Q86UP8,87,0,0,38,0
1260,Q6EKJ0,87,0,0,38,0
1261,Q5VZF2,59,0,0,28,0
1262,Q9HAK2,101,0,0,96,0
1263,Q9H4W6,101,0,0,90,0

In [37]:
l1,l2,l3,l4,l5= df2['102_CLabels_fractions_kappa'], df2['3_CLabels_fractions_kappa'], df2['3_CLabels_fractions'], df2['103_CLabels_fractions'], df2['ED_3_CLabels_fractions_kappa']

In [38]:
print (adjusted_rand_score(l1,l4))
print (adjusted_rand_score(l2,l3))
print (adjusted_rand_score(l2,l5))

0.47731707032273657
1.0
0.9269055053638761

In [39]:
print (fowlkes_mallows_score(l1,l4))
print (fowlkes_mallows_score(l2,l3))
print (fowlkes_mallows_score(l2,l5))

0.4851009174682367
1.0
0.9700021043735508