In [36]:
import localcider
from localcider.sequenceParameters import SequenceParameters
import pandas as pd

In [37]:
def kappa(sequence):
    
# create a SequenceParameters object with your amino acid sequence
    SeqOb = SequenceParameters(sequence)

    # carry out analysis
    return (SeqOb.get_kappa())

In [44]:
tf1 = pd.read_csv('BP1_properties.csv')
tf2 = pd.read_csv('BP2_properties.csv')

In [45]:
tf1['Kappa'] = tf1['BP Sequence'].apply(kappa)
tf2['Kappa'] = tf2['BP Sequence'].apply(kappa)

In [46]:
tf1

,Protein,UniProtID,Label,BP Sequence,Normalized HP Score,PONDR Score,A,C,D,E,...,R,S,T,V,W,Y,f+,f-,|f+ - f-|,Kappa
0,ANKZ1_HUMAN,Q9H8Y5,1.0,RFNLKQRLKDKPLLSALDFEKQSSTGDLSSISGSEDSDSASEEDLQ...,0.410635,0.408051,0.106349,0.014286,0.049206,0.088889,...,0.109524,0.066667,0.049206,0.041270,0.007937,0.017460,0.157143,0.138095,0.019048,0.187230
1,ANM3_HUMAN,O60678,1.0,QFNIDSMVHKHGLEFYGYIKLINFIRLKNPTVEYMNSIYNPVPWEK...,0.480121,0.097047,0.054348,0.017391,0.067391,0.069565,...,0.026087,0.073913,0.058696,0.084783,0.008696,0.045652,0.113043,0.136957,0.023913,0.182006
2,CHAP1_HUMAN,Q96JM3,1.0,GQSLLKCPRCNFESNFPRGFKKHLTHCQSRHNEEANKKLMEALEPP...,0.378846,0.473798,0.038462,0.057692,0.000000,0.134615,...,0.057692,0.057692,0.019231,0.000000,0.000000,0.000000,0.153846,0.134615,0.019231,0.294812
3,DZIP1_HUMAN,Q86YF9,1.0,TEENSHFEYQKNAQIEKLRSEIVVLKEELQLTRSELEAAHHASAVR...,0.398125,0.548910,0.049536,0.006192,0.047988,0.128483,...,0.038700,0.091331,0.047988,0.049536,0.009288,0.009288,0.142415,0.176471,0.034056,0.174022
4,LMBL1_HUMAN,Q9Y468,1.0,KAELSDSEASARKKNLSGFSPRKKPRHHGRIGRPPKYRKIPQEDFQ...,0.469565,0.234842,0.070652,0.027174,0.054348,0.048913,...,0.054348,0.103261,0.059783,0.076087,0.016304,0.010870,0.125000,0.103261,0.021739,0.260628
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,GTD2A_HUMAN,Q86UP8,45.0,KRKIDQEGRVFQEKWERAYFFVEVQNIPTCLICKQSMSVSKEYNLR...,0.463972,0.142121,0.039474,0.026316,0.050752,0.071429,...,0.041353,0.093985,0.056391,0.056391,0.016917,0.039474,0.125940,0.122180,0.003759,0.177373
1256,GTD2B_HUMAN,Q6EKJ0,45.0,KRKIDQEGRVFQEKWERAYFFVEVQNIPTCLICKQSMSVSKEYNLR...,0.464599,0.147374,0.037594,0.026316,0.048872,0.071429,...,0.043233,0.092105,0.058271,0.058271,0.016917,0.039474,0.129699,0.120301,0.009398,0.177591
1257,MBNL2_HUMAN,Q5VZF2,1.0,HLQAKIKAAQHQANQAAVAAQAAAAAATVMAFPPGALHPLPKRQAL...,0.494239,0.624139,0.185185,0.037037,0.007407,0.037037,...,0.022222,0.088889,0.066667,0.044444,0.000000,0.029630,0.059259,0.044444,0.014815,0.271567
1258,COE2_HUMAN,Q9HAK2,42.0,GNRNETPSDPVIIDRFFLKFFLKCNQNCLKTAGNPRDMRRFQVVLS...,0.470361,0.459942,0.061576,0.012315,0.032020,0.027094,...,0.054187,0.130542,0.054187,0.068966,0.004926,0.027094,0.088670,0.059113,0.029557,0.201666
1259,COE3_HUMAN,Q9H4W6,42.0,GNRNETPSDPVIIDRFFLKFFLKCNQNCLKNAGNPRDMRRFQVVVS...,0.472822,0.481032,0.075117,0.014085,0.030516,0.030516,...,0.049296,0.110329,0.058685,0.089202,0.004695,0.025822,0.082160,0.061033,0.021127,0.204319

In [47]:
tf2

,Protein,UniProtID,Label,BP Sequence,Normalized HP Score,PONDR Score,A,C,D,E,...,R,S,T,V,W,Y,f+,f-,|f+ - f-|,Kappa
0,ANKZ1_HUMAN,Q9H8Y5,1.0,MSPAPDAAPAPASISLFDLSADAPVFQGLSLVSHAPGEALARAPRT...,0.472300,0.826318,0.154930,0.014085,0.056338,0.070423,...,0.056338,0.154930,0.014085,0.028169,0.000000,0.000000,0.084507,0.126761,0.042254,0.144770
1,ANM3_HUMAN,O60678,1.0,MCSLASGATGGRGAVENEEDLPELSDSGDEAAWEDEDDADLPHGKQQ,0.389125,0.856934,0.127660,0.021277,0.148936,0.148936,...,0.021277,0.085106,0.021277,0.021277,0.021277,0.000000,0.042553,0.297872,0.255319,0.463370
2,CHAP1_HUMAN,Q96JM3,1.0,MEAFQELRKPSARLECDHCSFRGTDYENVQIHMGTIHPEFCDEMDA...,0.404674,0.765160,0.065129,0.016282,0.037992,0.082768,...,0.031208,0.147897,0.032564,0.042062,0.020353,0.012212,0.131615,0.120760,0.010855,0.179291
3,DZIP1_HUMAN,Q86YF9,1.0,MQAEAADWFSSMPFQKHVYYPLASGPEGPDVAVAAAAAGAASMACA...,0.477214,0.289516,0.116751,0.030457,0.045685,0.076142,...,0.045685,0.071066,0.040609,0.050761,0.010152,0.020305,0.116751,0.121827,0.005076,0.189801
4,LMBL1_HUMAN,Q9Y468,1.0,MHLVAGDSPGSGPHLPATAFIIPASSATLGLPSSALDVSCFPREPI...,0.423620,0.505674,0.075163,0.024510,0.058824,0.083333,...,0.037582,0.098039,0.040850,0.053922,0.024510,0.026144,0.080065,0.142157,0.062092,0.216636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1241,GTD2A_HUMAN,Q86UP8,45.0,MAQVAVSTLPVEEESSSETRMVVTFLVSALESMCKELAKSKAEVAC...,0.525888,0.217399,0.113402,0.061856,0.030928,0.113402,...,0.030928,0.072165,0.061856,0.154639,0.000000,0.020619,0.092784,0.144330,0.051546,0.162240
1242,GTD2B_HUMAN,Q6EKJ0,45.0,MAQVAVSTLPVEEESSSETRMVVTFLVSALESMCKELAKSKAEVAC...,0.525888,0.217399,0.113402,0.061856,0.030928,0.113402,...,0.030928,0.072165,0.061856,0.154639,0.000000,0.020619,0.092784,0.144330,0.051546,0.162240
1243,MBNL2_HUMAN,Q5VZF2,1.0,HLKTQLEINGRNNLIQQKTAAAMLAQQMQFMFPGTPLHPVPTFPVG...,0.523638,0.776070,0.088235,0.000000,0.000000,0.019608,...,0.019608,0.029412,0.127451,0.088235,0.000000,0.009804,0.049020,0.019608,0.029412,0.210366
1244,COE2_HUMAN,Q9HAK2,42.0,MFGIQDTLGRGPTLKEKSLGAEMDSVRSWVRNVGVVDANVAAQSGV...,0.436861,0.248535,0.051587,0.027778,0.055556,0.059524,...,0.079365,0.063492,0.051587,0.095238,0.003968,0.019841,0.138889,0.115079,0.023810,0.149321
1245,COE3_HUMAN,Q9H4W6,42.0,MFGIQENIPRGGTTMKEEPLGSGMNPVRSWMHTAGVVDANTAAQSG...,0.434309,0.377990,0.053435,0.026718,0.049618,0.064885,...,0.072519,0.057252,0.053435,0.080153,0.003817,0.022901,0.129771,0.114504,0.015267,0.139828

In [48]:
tf1.to_pickle('BP1_properties.pkl')
tf2.to_pickle('BP2_properties.pkl')

In [49]:
(tf1['Kappa']==tf2['Kappa']).unique()

ValueError: Can only compare identically-labeled Series objects